#!/usr/bin/python
from . import detile_jadwal_madin
from . import detile_jadwal_madrasah
from . import detile_kelas_madin
from . import detile_kelas_madrasah
from . import izin
from . import absen_madin
from . import siswa
from . import guru
from . import ustadz
from . import pengasuh
from . import kamar
from . import pelanggaran_madin
from . import pelanggaran_madrasah
from . import pelanggaran_pesantren
from . import pelanggaran
from . import matpel
from . import list_siswa
from . import absen
from . import absen_madrasah
from . import materi_madin
from . import materi_madrasah
from . import detile_materi_madrasah